### ISSUE TITLE
UseModelApi: Lacks of `self` for attributes in OCL Expression

### ISSUE THREAD

**Issue by ichxorya** [useocl/use#77]
**Describe the bug**
Unable to automatically find the `self` of USE Class attributes.

**To Reproduce**
Using Use Model Api:
- Create a class.
- Add some attributes to it.
- Write an OCL expression related to the class (that makes use of the attributes).
- Parse it with createPrePostCondition or createQueryOperation.

**Expected behavior**
Any .use specification can automatically understand the context (the attributes inside the class are automatically tagged `self`)

But while using the api, the `self`s must be defined already to be able to parse.

**Screenshots**
![image](https://github.com/useocl/use/assets/26222301/43c6ffa7-7547-4037-8239-0f8a97c89226)
![image](https://github.com/useocl/use/assets/26222301/a5d527d8-c6ee-4d5d-b013-7e019ce9c01b)
![image](https://github.com/useocl/use/assets/26222301/6189ee07-4eac-491b-afed-2a6dfea1d3cc)
![image](https://github.com/useocl/use/assets/26222301/4f6bfdb0-3fc9-44bf-aea4-0fe039c1a0bc)

It is runnable if I add `self` to the constraints:
![image](https://github.com/useocl/use/assets/26222301/6d91f585-c85d-486c-89f6-ba91865cfa51)

**Desktop (please complete the following information):**

- OS: Windows 10
- Java Version: OpenJDK17
- USE version: 7.1.0

**Note**

I'm developing an USE extension that parse non-use specifications.

**Comment by h-man2** [comment]
Thanks for submitting the issue. I was able to reproduce the behavior to confirm the bug.
The ModelAPI uses the `OCLCompiler` to create the Pre- and Postconditions, which is wrong.

If you need to proceed with your work, before the bug has been fixed, I suggest to have a look at the method `ASSLCompiler::compileInvariants`. It creates invariants, but conceptually it is the same. The key point their is, it uses a `Context` instead of a `SymTable` as it is done in `OCLCompiler::compileExpression`

**Comment by ichxorya** [comment]
Thank you, I'd try if asap
